### ISSUE TITLE
station_list able to return stations from all networks?

### ISSUE THREAD

**Issue by NicWayand** [jclark754/MesoPy#17]
I would like to grab station info from all networks within Washington State.

`stations = m.station_list(state='WA')`

Only returns 187 stations, which appear to only be Airports. Checking out the mesowest browser shows many more stations available. Is it possible to retrieve other network station info using station_list() ?

**Comment by ghost** [comment]
Hey @NicWayand,
The offending line is `kwargs['network'] = '1,2'`, line 479. I accidentally set the networks to only be NWS and RAWs stations for some debugging purpose many months ago. This has been fixed in version 2+, just note that some of the functions have been renamed like `station_list()` is now `metadata()`.

**Comment by NicWayand** [comment]
Thanks @jclark754, I wasn't aware that I was so behind! Pulled and now metadata() works great, grabs all WA stations.
